"""
utils/helpers.py
-----------------
Generic helper functions shared across agents. Currently one function:
`execute_readonly_query`, the safety layer between an LLM-generated SQL
string and the actual database.

WHY THIS LIVES IN utils/ RATHER THAN INSIDE sql_agent.py
    `execute_readonly_query` is a generic, reusable safety utility -- "run
    this string against SQLite, but only if it's a single safe SELECT" --
    that has nothing agent-specific about it. Keeping it in utils/ instead
    of src/agents/sql_agent.py makes that reusability explicit and keeps
    sql_agent.py focused on the agent's own reasoning (generate SQL,
    interpret results), not on SQL-string validation mechanics.

WHY A SELECT-ONLY SAFETY GUARD AT ALL
    A SQL string generated by an LLM is untrusted input -- the model can
    be wrong, or manipulated via prompt injection in retrieved content.
    Before this function ever hands a string to sqlite3, it checks that
    the string is a single, standalone SELECT statement and rejects
    anything else. This matters even more with a smaller, cheaper model
    like Nova Micro, which is more likely to produce a malformed or overly
    literal query than a larger model would.
"""

import re
import sqlite3
from typing import List, Tuple

from config.settings import DB_PATH


def execute_readonly_query(sql: str, db_path=None) -> Tuple[List[str], List[Tuple]]:
    """Safely validate and execute a single SELECT statement.

    Why we validate BEFORE executing:
        `sql` originates from an LLM's response -- untrusted input. We
        reject anything that is not a single, standalone SELECT statement:
        no semicolon-separated multi-statements, and no INSERT / UPDATE /
        DELETE / DROP / ALTER / ATTACH / PRAGMA / CREATE / REPLACE
        keywords anywhere in the string.

    Args:
        sql: The SQL string to validate and execute.
        db_path: Path to the SQLite database file. Defaults to None, which
            resolves to config.settings.DB_PATH *at call time* (not at
            import time) -- this matters because tests monkeypatch
            DB_PATH to point at a throwaway file, and a plain
            `db_path=DB_PATH` default parameter would have captured the
            real path once, permanently, when this module was first
            imported.

    Returns:
        (column_names, rows) on success.

    Raises:
        ValueError: if `sql` fails the SELECT-only safety check.
        sqlite3.Error: if the (validated) query fails to execute -- e.g. a
            syntax error or an unknown column. This is allowed to
            propagate so the calling agent (sql_agent.py) can catch it and
            mark the attempt as failed, rather than this function silently
            swallowing real bugs.
    """
    if db_path is None:
        db_path = DB_PATH

    normalized = sql.strip().rstrip(";").strip()

    if not re.match(r"(?is)^\s*SELECT\b", normalized):
        raise ValueError("Only single SELECT statements are allowed.")
    if ";" in normalized:
        raise ValueError("Multiple statements are not allowed.")
    forbidden_pattern = r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|ATTACH|PRAGMA|CREATE|REPLACE)\b"
    if re.search(forbidden_pattern, normalized, flags=re.IGNORECASE):
        raise ValueError("Query contains a disallowed keyword.")

    conn = sqlite3.connect(db_path)
    try:
        cur = conn.cursor()
        cur.execute(normalized)
        rows = cur.fetchall()
        columns = [d[0] for d in cur.description] if cur.description else []
        return columns, rows
    finally:
        conn.close()
